layout_spectrum: 0.7022824
typography_spectrum: 0.9229788
color:
  saturation: 0.6231812
  lightness: 0.340129
  brandStrength: 0.6499046
  rhythmicContrast: 0.4284538
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Test from AppStore
